name: Sync to Launchpad

# We only care about syncing release and trunk branches
on:
  push:
    branches:
      - master
      - develop
      - '[0-9]+'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: git config user.name "CI Bot"
      - run: git config user.email "nextcloud-snappy-bot@git.launchpad.net"
      - run: git remote add deploy git+ssh://nextcloud-snappy-bot@git.launchpad.net/nextcloud-snap

      - run: echo "Requesting build/deploy of ${GITHUB_REF#refs/heads/}..."
      - run: git push deploy ${GITHUB_REF#refs/heads/} --force